### ISSUE TITLE
does newer Unity version work?

### ISSUE THREAD

**Issue by NeoForce0** [PacktPublishing/Complete-Unity-2018-Game-Development#1]
Hello, I am going through the Unity Game Development tutorials with a newer version 2018.3.0f2. The first 2 chapters worked well until I reached the 3rd chapter on post processing. Basically, Unity loaded the elevation map OK but without texture and then it said its missing prefab such as the tree... Is this due to the version incompatibility?

Thx,
Ron

**Comment by Dragonkilz** [comment]
I'm having the same issues with the post processing chapter, I'm currently using 2018.1.9f2, i have the project loaded but nothing is working, I have missing prefab in the hierarchy, when i try to move ahead and add the post process layer component, i cannot select the postprocessing layer. this chapter has been a headache so far. Any updates or answers?
